export const hebrew = {
  loading: 'טוען...',
  error: 'שגיאה',
  success: 'הצלחה',
  cancel: 'ביטול',
  save: 'שמור',
  delete: 'מחק',
  edit: 'ערוך',
  add: 'הוסף',
  search: 'חיפוש',
  filter: 'סינון',
  sort: 'מיון',
  yes: 'כן',
  no: 'לא',
  ok: 'אישור',
  back: 'חזור',
  next: 'הבא',
  previous: 'הקודם',
  close: 'סגור',
  submit: 'שלח',
  retry: 'נסה שוב',
  refresh: 'רענן',
  logout: 'התנתק'
};
