-- The canonical schema is now defined in supabase/migrations/20251015_000000_init.sql.
-- This file remains as a pointer for tooling that previously referenced supabase/schema.sql.
-- Update the baseline via `node scripts/collapse-migrations.cjs --stamp <yyyymmdd>` and
-- re-run `npx supabase db reset` to sync local environments.
